{
 "title": "Mini Cloud",
 "tags": [ "node-exporter-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg by (instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter\",instance=\"$instance\",cluster=\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance, device, mountpoint, fstype) (\n  node_filesystem_avail_bytes{device=~\"/dev/(sd|nvme).*\",fstype!~\"tmpfs|rootfs\",mountpoint!~\"/(boot|run|sys|proc|dev).*\"}\n)\n/\nmax by (instance, device, mountpoint, fstype) (\n  node_filesystem_size_bytes{device=~\"/dev/(sd|nvme).*\",fstype!~\"tmpfs|rootfs\",mountpoint!~\"/(boot|run|sys|proc|dev).*\"}\n)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\",  mountpoint!~\"/boot.*\", device=~\"/dev/(sd|nvme).*\"})"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!~\"/boot.*\", device=~\"/dev/(sd|nvme).*\"})\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Node CPU Usage"
    },
    {
     "expr": "sum by(namespace, pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total System Memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\"}\n- (\n  node_memory_MemFree_bytes{job=\"node-exporter\"}\n  + node_memory_Buffers_bytes{job=\"node-exporter\"}\n  + node_memory_Cached_bytes{job=\"node-exporter\"}\n)",
     "legendFormat": "Used System Memory"
    },
    {
     "expr": "sum by(container, namespace) (container_memory_usage_bytes{container!~\"\", namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}: {{container}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Total Bytes/Sec"
    },
    {
     "expr": "sum by(namespace, pod) (rate(container_network_receive_bytes_total{namespace!=\"\", pod!=\"\", interface!=\"lo\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_bytes_total{device!=\"lo\"}[$__rate_interval])\n)",
     "legendFormat": "Total Tx Bytes/Sec"
    },
    {
     "expr": "sum by(pod, namespace) (rate(container_network_transmit_bytes_total{pod!=\"\", namespace=~\"$namespace\", interface!=\"lo\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}: {{pod}}"
    }
   ]
  }
 ]
}