- name: Set Privilege Escalation Requirements
  ansible.builtin.set_fact:
    use_sudo: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ unix_packages }}"
    update_cache: true
    state: present
  become: "{{ use_sudo }}"
  when: unix_packages is defined

- name: Install Selected Packages (Mac/Linux)
  ansible.builtin.package:
    name: "{{ packages | default([]) }}"
    update_cache: true
    state: present
  become: "{{ use_sudo }}"
  when: packages is defined

- name: Include Fedora/RedHat Tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Include Darwin Tasks
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'
