# Default values for plex.

replicaCount: 1

image:
  repository: linuxserver/plex
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Plex claim token from https://plex.tv/claim
claimToken: ""

# Set the timezone of the plex server
timezone: UTC

plexPort: "32400"

service:
  type: ClusterIP
  port: 32400
  targetPort: 32400
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: plex.livingroom.cloud
    external-dns.alpha.kubernetes.io/target: "174.44.105.210"
  hosts:
  - host: plex.livingroom.cloud
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: plex.livingroom.cloud-tls
    hosts:
    - plex.livingroom.cloud

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: http-gateway
    namespace: kgateway-system
  hostnames:
  - "plex.livingroom.cloud"
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /

persistence:
  movies:
    mountPath: /data/Movies
    storageClass: "local-storage"
    size: 100Gi
    accessMode: ReadWriteMany
  series:
    mountPath: /data/Series
    storageClass: "local-storage"
    size: 100Gi
    accessMode: ReadWriteMany
  config:
    mountPath: /config
    storageClass: "local-storage"
    size: 3Gi
    accessMode: ReadWriteMany

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
