apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: plex
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: PLEX_CLAIM # TODO: move this to a secret?
              value: "{{ .Values.claimToken }}"
            - name: PMS_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            {{- range $key, $vol := .Values.persistence }}
            {{- if ne ($vol.enabled | default true) false }}
            - name: {{ include "plex.persistenceVolumeName" $key }}
              mountPath: {{ $vol.mountPath | quote }}
            {{- end }}
            {{- end }}
      volumes:
        {{- range $key, $vol := .Values.persistence }}
        {{- if ne ($vol.enabled | default true) false }}
        - name: {{ include "plex.persistenceVolumeName" $key }}
          persistentVolumeClaim:
            claimName: {{ include "plex.persistenceClaimName" (dict "root" $ "key" $key) }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
