{{- range $key, $vol := .Values.persistence }}
{{- if ne ($vol.enabled | default true) false }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.persistenceClaimName" (dict "root" $ "key" $key) }}
  labels:
    app: {{ template "plex.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $key | kebabcase }}
spec:
  accessModes:
  - {{ $vol.accessMode | quote }}
  resources:
    requests:
      storage: {{ $vol.size | quote }}
  storageClassName: {{ $vol.storageClass | quote }}
{{- end }}
{{- end }}
