# Values for plex.livingroom.cloud

replicaCount: 1

image:
  repository: linuxserver/plex
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}

# Plex claim token from https://plex.tv/claim
claimToken: "claim-K1NthaFNrh-ZgzMxhqsn"

# Set the timezone of the plex server
timezone: America/New_York

plexPort: "32400"

service:
  type: ClusterIP
  port: 32400
  targetPort: 32400
  protocol: TCP

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
  - name: http-gateway
    namespace: kgateway-system
  hostnames:
  - "plex.authriz.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /

persistence:
  movies:
    mountPath: /data/Movies
    storageClass: "local-path"
    size: 1Gi
    accessMode: ReadWriteOnce
  series:
    mountPath: /data/Series
    storageClass: "local-path"
    size: 1Gi
    accessMode: ReadWriteOnce
  config:
    mountPath: /config
    storageClass: "local-path"
    size: 1Gi
    accessMode: ReadWriteOnce

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100

nodeSelector: {}

tolerations: []

affinity: {}
